#!/bin/sh

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ\//abcdefghijklmnopqrstuvwxyz-/"
}

OS=`lowercase \`uname -s\``
MACH=`uname -m`

#If the system is debian based, the debian version is included
if [ -f /etc/debian_version ]
then
    DEBIAN=`lowercase \`cat /etc/debian_version\``
    archive_file="domoticz_${OS}_${MACH}_debian-${DEBIAN}.tgz"
else
    archive_file="domoticz_${OS}_${MACH}.tgz"
fi

#Generate the archive
echo "Generating Archive: ${archive_file}..."

if [ -f ${archive_file} ];
then
  rm ${archive_file}
fi

tar -zcvf ${archive_file} domoticz History.txt License.txt updatedomo svnversion.h domoticz.sh www/ scripts/
echo "Archive made (${archive_file})..."

#################################
#echo "Uploading to sourceforge..."
#scp svnversion.h History.txt ${archive_file} username@web.sourceforge.net:/home/project-web/domoticz/htdocs
#################################

echo "Done!"
