#!/bin/bash

lowercase(){
    echo "$1" | sed "y/ABCDEFGHIJKLMNOPQRSTUVWXYZ\//abcdefghijklmnopqrstuvwxyz-/"
}

#Identify Debian Version
identify_debian(){
    DEB_VERSION=`lowercase \`cat /etc/debian_version\``

    case "$DEB_VERSION" in
      *squeeze*) echo "squeeze" ;;
      *wheezy*)  echo "wheezy" ;;
      *jessie*)  echo "jessie" ;;
      5.0*) echo "lenny" ;;
      6.0*) echo "squeeze" ;;
      7.0*) echo "wheezy" ;;
      7.1*) echo "wheezy" ;;
      8.0*) echo "jessie" ;;
      *)    echo "other" ;;
    esac
}

identify_system_type(){
    ARCH=`getconf LONG_BIT`
    echo "${ARCH}bits"
}

identify_cpu_family(){
    CPU=`lowercase \`uname -m\``
    case "$CPU"  in
      i*86)   echo "x86" ;;
      x86_64) echo "x86_64" ;;
      *)      echo "$CPU" ;;
    esac
}

MACH=`identify_system_type`
ARCH=`identify_cpu_family`

#If the system is debian based, the debian version is included
if [ -f /etc/debian_version ]
then
    VERSION=`identify_debian`
    archive_file="domoticz_${ARCH}_${MACH}_debian-${VERSION}.tgz"
else
    archive_file="domoticz_${ARCH}_${MACH}.tgz"
fi

#Generate the archive
echo "Generating Archive: ${archive_file}..."

if [ -f ${archive_file} ];
then
  rm ${archive_file}
fi

tar -zcvf ${archive_file} domoticz History.txt License.txt updatedomo svnversion.h domoticz.sh www/ scripts/
echo "Archive made (${archive_file})..."

#################################
#echo "Uploading to sourceforge..."
#scp svnversion.h History.txt ${archive_file} username@web.sourceforge.net:/home/project-web/domoticz/htdocs
#################################

echo "Done!"
